cc_test(
    name = "stopwatch_test",
    srcs = ["stopwatch_test.cpp", "lest.hpp"],
    deps = ["//ken3:stopwatch"],
)

cc_test(
    name = "pystr_test",
    srcs = ["pystr_test.cpp", "lest.hpp"],
    deps = ["//ken3:pystr"],
)

cc_test(
    name = "metric_test",
    srcs = ["metric_test.cpp", "lest.hpp"],
    deps = ["//ken3:metric"],
)

