cc_test(
    name = "angle_test",
    srcs = ["angle_test.cpp", "lest.hpp"],
    deps = ["//ken3:angle"],
    size = "small",
)

cc_test(
    name = "bits_test",
    srcs = ["bits_test.cpp", "lest.hpp"],
    deps = ["//ken3:bits"],
    size = "small",
)

cc_test(
    name = "biunique_map_test",
    srcs = ["biunique_map_test.cpp", "lest.hpp"],
    deps = ["//ken3:biunique_map"],
    size = "small",
)

cc_test(
    name = "cast_test",
    srcs = ["cast_test.cpp", "cast/int_cast_test.cpp", "lest.hpp"],
    deps = ["//ken3:cast"],
    size = "small",
)

cc_test(
    name = "metric_test",
    srcs = ["metric_test.cpp", "lest.hpp"],
    deps = ["//ken3:metric"],
    size = "small",
)

cc_test(
    name = "pyloop_test",
    srcs = ["pyloop_test.cpp", "pyloop/enumerate_test.cpp", "pyloop/range_test.cpp", "pyloop/zip_test.cpp", "lest.hpp"],
    deps = ["//ken3:pyloop"],
    size = "small",
)

cc_test(
    name = "pystr_test",
    srcs = ["pystr_test.cpp", "lest.hpp"],
    deps = ["//ken3:pystr"],
    size = "small",
)

cc_test(
    name = "stopwatch_test",
    srcs = ["stopwatch_test.cpp", "lest.hpp"],
    deps = ["//ken3:stopwatch"],
    size = "small",
)

cc_test(
    name = "type_util_test",
    srcs = ["type_util_test.cpp", "type_util/e2i_test.cpp", "type_util/array_size_test.cpp", "type_util/array_get_test.cpp", "lest.hpp"],
    deps = ["//ken3:type_util"],
    size = "small",
)

