cc_library(
    name = "angle",
    hdrs = ["angle.hpp"],
    visibility = ["//unittest:__pkg__"],
)

cc_library(
    name = "bits",
    srcs = ["bits.cpp"],
    hdrs = ["bits.hpp"],
    visibility = ["//unittest:__pkg__"],
)

cc_library(
    name = "biunique_map",
    hdrs = ["biunique_map.hpp"],
    visibility = ["//unittest:__pkg__"],
)

cc_library(
    name = "metric",
    hdrs = ["metric.hpp"],
    visibility = ["//unittest:__pkg__"],
)

cc_library(
    name = "pystr",
    srcs = ["pystr.cpp"],
    hdrs = ["pystr.hpp"],
    visibility = ["//unittest:__pkg__"],
)

cc_library(
    name = "stopwatch",
    srcs = ["stopwatch.cpp"],
    hdrs = ["stopwatch.hpp"],
    visibility = ["//unittest:__pkg__"],
)

cc_library(
    name = "type_util",
    hdrs = ["type_util.hpp"],
    visibility = ["//unittest:__pkg__"],
)

